# Generated by Django 5.0.6 on 2024-07-21 18:13

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0005_product_life_product_mfd_product_stock_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='I am amazing Vendor', null=True),
        ),
    ]
