# Generated by Django 5.0.6 on 2024-08-10 14:58

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0010_address_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(default='Country, City 123', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+12 345 67 89', max_length=128, region=None),
            preserve_default=False,
        ),
    ]
