# Generated by Django 5.0.6 on 2024-08-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0015_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='off',
            field=models.DecimalField(decimal_places=2, default='1.99', max_digits=99999),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount',
            field=models.IntegerField(default=1),
        ),
    ]
