# Generated by Django 5.0.6 on 2024-08-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0016_coupon_off_alter_coupon_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='coupons',
            field=models.ManyToManyField(blank=True, to='shopper.coupon'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='off',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=99999, null=True),
        ),
    ]
